#!/usr/bin/env python3
"""
feedback_store.py — the single source of truth for human corrections.

The deck (serve_deck.py), the deck builder (build_records.py) and the agent
(scrape_agent_adk.py) all import this so they agree on (a) how an entry is
identified and (b) where flags live. Flags persist in feedback.json, which is
NEVER regenerated by the pipeline — so a correction made in the deck survives the
next catalogue.json rewrite and the next agent run.

A flag's `reason` is one of: "expired" | "duplicate" | "hallucinated".
Identity is `block_key(cat, name)` — lowercase, punctuation-stripped — the same
normalisation build_records uses for dupe collapsing, so the deck, the builder and
the agent merge all key the same way.
"""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path

FEEDBACK_FILE = Path(__file__).parent / "feedback.json"

VALID_REASONS = {"expired", "duplicate", "hallucinated"}


def normalize(name: str) -> str:
    """Canonical name normaliser (matches build_records._norm_name)."""
    return re.sub(r"[^a-z0-9]", "", (name or "").strip().lower())


def block_key(cat: str, name: str) -> str:
    """Stable id shared by the deck, the builder and the agent merge."""
    return f"{cat}|{normalize(name)}"


def load_flags() -> list[dict]:
    """Return the list of flag records (empty if the file is missing/corrupt)."""
    if not FEEDBACK_FILE.exists():
        return []
    try:
        data = json.loads(FEEDBACK_FILE.read_text())
        flags = data.get("flags", [])
        return flags if isinstance(flags, list) else []
    except Exception:
        return []


def _save(flags: list[dict]) -> None:
    FEEDBACK_FILE.write_text(json.dumps({"flags": flags}, indent=2, ensure_ascii=False) + "\n")


def add_flag(cat: str, title: str, reason: str, note: str = "") -> dict:
    """Add (or update) a flag for an entry, keyed by block_key. Idempotent per id."""
    reason = (reason or "").strip().lower()
    if reason not in VALID_REASONS:
        raise ValueError(f"reason must be one of {sorted(VALID_REASONS)}, got {reason!r}")
    fid = block_key(cat, title)
    flags = [f for f in load_flags() if f.get("id") != fid]   # replace any existing
    record = {
        "id": fid,
        "cat": cat,
        "title": title,
        "reason": reason,
        "note": note or "",
        "ts": datetime.now(timezone.utc).isoformat(),
    }
    flags.append(record)
    _save(flags)
    return record


def remove_flag(fid: str) -> bool:
    """Un-flag by id. Returns True if something was removed."""
    flags = load_flags()
    kept = [f for f in flags if f.get("id") != fid]
    if len(kept) == len(flags):
        return False
    _save(kept)
    return True


def blocked_ids(reasons: set[str] | None = None) -> set[str]:
    """Set of block_keys currently flagged. Optionally filter by reason(s)."""
    return {
        f["id"] for f in load_flags()
        if f.get("id") and (reasons is None or f.get("reason") in reasons)
    }


def flags_by_reason() -> dict[str, list[str]]:
    """{reason: [title, ...]} — used to build the agent's OPERATOR CORRECTIONS block."""
    out: dict[str, list[str]] = {}
    for f in load_flags():
        out.setdefault(f.get("reason", "other"), []).append(f.get("title", ""))
    return out
